ref: replace if-else chain with dict lookup for response computation
meta-llama/PurpleLlama pull request #32
Opened 2024-04-23 19:23 UTC by iw4p

The new code won't waste time creating LLMs if none were specified, and can raise a ValueError right away.

2024-04-24 18:52 UTC, SimonWan requested changes
This change does not serve exactly the same purpose because we check `llms_under_test` in addition to `args.llm_under_test`. 
It would be appropriate to extend the if condition to check both. 

If you decide to update the commit, please also skip the middle commit in this chain, as it appears mergeable with this one. Thank you for your proposal!

2024-04-24 18:59 UTC, SimonWan reviewed
Actually I also just published the change for this format, so you can skip both base commits and then focus on the if condition udpate.

2024-04-24 19:04 UTC, iw4p commented
Hi SimonWan! Sure, I will ignore the black reformatting commits and just change the if statement. Thank you.

2024-04-24 19:22 UTC, iw4p commented
Hey Simon! Both raise ValueErrors for `materialized_llms_under_test` and `args.llm_under_test `have been added. I ignored the black formatting commits too.

2024-04-25 09:24 UTC, Seefalfares approved these changes

2024-04-26 15:03 UTC, SimonWan requested changes
Please address my comments as the current version may still raise unexpected errors. Thank you.

2024-04-26 16:15 UTC, iw4p commented
> Please address my comments as the current version may still raise unexpected errors. Thank you.

Hi Simon! Thank you. I skipped the old commits and handled the error checking/controlling as you asked.

2024-04-26 17:02 UTC, SimonWan approved these changes
Thanks for the update! LGTM

2024-04-26 17:44 UTC, closed without merging